<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>72f35cdd-adb1-4655-81df-685f297e0bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71add2fb-63a5-43ae-beba-5cb5dc5437e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-blue float-left</value>
      <webElementGuid>8b52cd94-5c7b-4361-98db-acf17885806c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05eac25a-650f-4ace-a7a1-c2a89e73306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a7e4daa1-b08e-4b21-a4b4-377504947c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>ca0edbe4-a0e1-4c07-abe7-7811384f2d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>723e63a3-64a3-44f6-b7b8-1c77b818798b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_body&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row content-bg&quot;]/div[@class=&quot;col-12 col-sm-7&quot;]/div[@class=&quot;content-area&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-9 offset-xl-3&quot;]/login-view[@class=&quot;login-box&quot;]/login-form[1]/div[@class=&quot;col-12&quot;]/div[@class=&quot;content-area-content&quot;]/form[1]/fieldset[1]/div[@class=&quot;form-group form-control-custom mt-20 clearfix&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-blue float-left&quot;]</value>
      <webElementGuid>bb257d9a-7ca5-44ca-ba4a-b3c90c6cdf0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='button']</value>
      <webElementGuid>0c18e06f-833d-4d31-bb25-d88f9f9749b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_body']/div/div[5]/div/div/div/div/div/login-view/login-form/div/div[2]/form/fieldset/div[3]/div[2]/button[2]</value>
      <webElementGuid>ad117bf6-e73e-4032-bd1d-91b80ca4979e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5ec73407-0ef9-4f5b-b81b-21d79cd47d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and @type = 'submit' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>4520edce-f28b-4f8e-99c0-71bcf90b5eb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
